"""
Utilities for naming SOAP features.

These helpers intentionally avoid coupling to the legacy code in the root
directory so the new pipeline can evolve independently.
"""

from __future__ import annotations

from itertools import combinations_with_replacement
from typing import Iterable, List, Sequence

from dscribe.descriptors import SOAP


def normalise_species(species: Iterable[str]) -> List[str]:
    """Return a sorted list of unique species symbols."""
    return sorted(set(species))


def feature_labels(soap: SOAP, species: Sequence[str]) -> List[str]:
    """
    Produce deterministic column names for every feature index generated by
    ``soap`` when called with ``average='off'`` and the provided species list.

    The implementation mirrors :func:`SOAP.get_location` to map contiguous slices
    belonging to each pair channel onto human-readable labels.
    """
    ordered_species = normalise_species(species)
    labels: List[str] = []

    for sp1, sp2 in combinations_with_replacement(ordered_species, 2):
        slc = soap.get_location((sp1, sp2))
        block_size = slc.stop - slc.start
        for idx in range(block_size):
            labels.append(f"{sp1}-{sp2}_{idx}")

    return labels
